spring:
  main:
    web-application-type: none

#Step 1: Configure OAuth Consent Screen via Google CLoud -> API&Services -> OAuth Consent Screen
#Step 2: Configure Credentials via Google CLoud -> API&Services -> Credentials
#Step 3: After creading the OAuth Credentials, DOwnload the JSON File that contains the info and fill out below
#Step 4: Add configuration Details Below - DO NOT COMMIT THIS TO GITHUB AFTER FILLING OUT
google:
  api:
    clientid: ${CLIENT_ID}
    clientsecret: ${CLIENT_SECRET}
    authuri: "https://accounts.google.com/o/oauth2/auth"
    tokenuri: "https://oauth2.googleapis.com/token"
    redirecturi: ${REDIRECT_URI} #Ensure port in this redirect URI is the same as the one specified in the docker run command - See README.md
